name: Semantic Release
on: [push, pull_request]
jobs:
  release:
    name: Semantic Release Process
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
      - run: npm ci
