name: GitHub Actions Demo
on: [push, pull_request]
jobs:
  test:
    name: Testing with NodeJS v${{ matrix.node }}
    runs-on: ubuntu-latest
    continue-on-error: ${{matrix.stable == false}}
    strategy:
      fail-fast: false
      matrix:
        node: ['13', '14', '15']
        stable: [true]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test
  release:
    name: Semantic Release Process
    if: ${{github.ref == 'refs/heads/main' && github.event_name == 'pull_request'}}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "RUNNING SEMANTIC RELEASE"
