name: GitHub Actions Demo
on:
  push:
    branches:
      - 'develop'
      - 'feat/**'
      - 'fix/**'
    tags-ignore:
      - '**'
  pull_request:
    types: [closed]
    tags-ignore:
      - '**'
jobs:
  karma_test:
    name: Testing with NodeJS v${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: ['12', '13', '14']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test
  release:
    name: Semantic Release Process
    needs: karma_test
    if: github.base_ref == 'main' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: echo "RUNNING SEMANTIC RELEASE"
